name: Custom Kernel Build

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Compiler Cache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ runner.os }}-kernel-${{ github.sha }}
          restore-keys: ${{ runner.os }}-kernel-
          max-size: 3G

      - name: Run Build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export PATH="/usr/lib/ccache:$PATH"
          bash build.sh
